--1) 평점이 3.0에서 4.0사이의 학생을 검색하라(between and)
SELECT S.*
FROM STUDENT S
WHERE S.AVR BETWEEN 3.0 AND 4.0;

--2) 1994년에서 1995년까지 부임한 교수의 명단을 검색하라(between and)
SELECT P.*
FROM PROFESSOR P
WHERE P.HIREDATE BETWEEN TO_DATE('19940101 00:00:00','YYYYMMDD HH24:mi:ss')
    AND TO_DATE('19951231 12:59:59','YYYYMMDD HH24:mi:ss');

--3) 화학과와 물리학과, 생물학과 학생을 검색하라(in)
SELECT S.*
FROM STUDENT S
WHERE S.MAJOR IN ('화학','물리','생물');

--4) 정교수와 조교수를 검색하라(in)
SELECT P.*
FROM PROFESSOR P
WHERE P.ORDERS IN ('정교수','조교수');

--5) 학점수가 1학점, 2학점인 과목을 검색하라(in)
SELECT C.*
FROM COURSE C
WHERE C.ST_NUM IN (1,2);

--6) 1, 2학년 학생 중에 평점이 2.0에서 3.0사이인 학생을 검색하라(between and)
SELECT S.*
FROM STUDENT S
WHERE S.SYEAR IN (1,2) AND S.AVR BETWEEN 2.0 AND 3.0;

--7) 화학, 물리학과 학생 중 1, 2 학년 학생을 성적순으로 검색하라(in)
SELECT S.*
FROM STUDENT S
WHERE S.MAJOR IN ('화학','물리') AND S.SYEAR IN (1,2) ORDER BY S.AVR DESC ;

--8) 부임일이 1995년 이전인 정교수를 검색하라(to_date)
SELECT P.*
FROM PROFESSOR P
WHERE P.HIREDATE < TO_DATE('19950101','YYYYMMDD') AND P.ORDERS = '정교수';



--1) 송강 교수가 강의하는 과목을 검색한다
SELECT C.CNAME, P.PNAME
FROM COURSE C
JOIN PROFESSOR P
ON C.PNO = P.PNO AND P.PNAME = '송강';

--2) 화학 관련 과목을 강의하는 교수의 명단을 검색한다
SELECT P.*, C.CNAME
FROM PROFESSOR P
JOIN COURSE C
ON P.PNO = C.PNO AND C.CNAME LIKE ('%화학%');

--3) 학점이 2학점인 과목과 이를 강의하는 교수를 검색한다
SELECT P.*,C.ST_NUM
FROM PROFESSOR P
JOIN COURSE C
ON C.ST_NUM = 2 AND C.PNO = P.PNO;

--4) 화학과 교수가 강의하는 과목을 검색한다
SELECT C.*, P.SECTION
FROM COURSE C
JOIN PROFESSOR P
ON P.SECTION = '화학' AND C.PNO = P.PNO;

--5) 화학과 1학년 학생의 기말고사 성적을 검색한다
SELECT SC.RESULT, ST.SYEAR
FROM SCORE SC
JOIN STUDENT ST
ON ST.SYEAR = 1 AND ST.MAJOR = '화학' AND ST.SNO = SC.SNO;

--6) 일반화학 과목의 기말고사 점수를 검색한다
SELECT S.RESULT, C.CNAME
FROM SCORE S
JOIN COURSE C
ON C.CNAME = '일반화학' AND C.CNO = S.CNO;

--7) 화학과 1학년 학생의 일반화학 기말고사 점수를 검색한다
SELECT SC.RESULT, ST.MAJOR, ST.SYEAR, C.CNO, ST.SNAME, C.CNAME
FROM SCORE SC
JOIN STUDENT ST
ON ST.SNO = SC.SNO
JOIN COURSE C
ON C.CNO = SC.CNO
AND ST.SYEAR = 1
AND ST.MAJOR = '화학'
AND C.CNAME = '일반화학';


--8) 화학과 1학년 학생이 수강하는 과목을 검색한다
SELECT DISTINCT C.CNO, C.CNAME, ST.SYEAR, ST.MAJOR
FROM SCORE SC
JOIN STUDENT ST
ON SC.SNO = ST.SNO
JOIN COURSE C
ON C.CNO = SC.CNO AND ST.SYEAR = 1 AND ST.MAJOR = '화학';


--9) 유기화학 과목의 평가점수가 F인 학생의 명단을 검색한다
SELECT DISTINCT ST.SNAME, SCG.GRADE, SC.RESULT
FROM SCORE SC
JOIN STUDENT ST
ON SC.SNO = ST.SNO
JOIN COURSE C
ON C.CNO = SC.CNO AND C.CNAME = '유기화학'
JOIN SCGRADE SCG
ON SCG.GRADE = 'F' AND SC.RESULT BETWEEN SCG.LOSCORE AND SCG.HISCORE





--1) 학생중에 동명이인을 검색한다
SELECT DISTINCT S.*
FROM STUDENT S
JOIN STUDENT ST
ON S.SNAME = ST.SNAME AND S.SNO != ST.SNO
ORDER BY S.SNO;

--2) 전체 교수 명단과 교수가 담당하는 과목의 이름을 학과 순으로 검색한다
SELECT P.*, C.CNAME
FROM PROFESSOR P
JOIN COURSE C
ON P.PNO = C.PNO
ORDER BY P.SECTION

--3) 이번 학기 등록된 모든 과목과 담당 교수의 학과 순으로 검색한다
SELECT C.*, P.PNAME,P.SECTION
FROM COURSE C
JOIN PROFESSOR P
ON C.PNO = P.PNO
ORDER BY P.SECTION;



--1) 각 과목의 과목명과 담당 교수의 교수명을 검색하라
SELECT C.CNAME, P.PNAME
FROM COURSE C
LEFT JOIN PROFESSOR P
ON C.PNO = P.PNO;

--2) 화학과 학생의 기말고사 성적을 모두 검색하라
SELECT SC.RESULT, ST.MAJOR
FROM SCORE SC
JOIN STUDENT ST
ON SC.SNO = ST.SNO AND ST.MAJOR = '화학';

--3) 유기화학과목 수강생의 기말고사 시험점수를 검색하라
SELECT SC.RESULT, C.CNAME
FROM SCORE SC
JOIN COURSE C
ON SC.CNO = C.CNO AND C.CNAME = '유기화학';

--4) 화학과 학생이 수강하는 과목을 담당하는 교수의 명단을 검색하라
SELECT DISTINCT P.*, C.CNAME
FROM PROFESSOR P
JOIN COURSE C
ON P.PNO = C.PNO
JOIN SCORE SC
ON SC.CNO = C.CNO
JOIN STUDENT ST
ON ST.SNO = SC.SNO AND ST.MAJOR = '화학';


--5) 모든 교수의 명단과 담당 과목을 검색한다
SELECT P.*, C.CNAME
FROM PROFESSOR P
LEFT JOIN COURSE C
ON C.PNO = P.PNO

--6) 모든 교수의 명단과 담당 과목을 검색한다(단 모든 과목도 같이 검색한다)
SELECT P.*, C.CNAME
FROM PROFESSOR P
         FULL JOIN COURSE C
                   ON C.PNO = P.PNO;
SELECT *
FROM PROFESSOR