--1) CNO이 PK인 COURSE_PK 테이블을 생성하세요.(1번 방식으로)


--2) PNO이 PK인 PROFESSOR_PK 테이블을 생성하세요.(2번 방식으로)


--3) PF_TEMP 테이블에 PNO을 PK로 추가하세요.


--4) COURSE_PROFESSOR 테이블에 CNO, PNO을 PK로 추가하세요.


--5) BOARD_NO(NUMBER)를 PK로 갖으면서 BOARD_TITLE(VARCHAR2(200)), BOARD_CONTENT(VARCHAR2(2000)), 
--   BOARD_WRITER(VARCHAR2(20)), BOARD_FRGT_DATE(DATE), BOARD_LMDF_DATE(DATE) 컬럼을 갖는 T_BOARD 테이블을 생성하세요.


--6) BOARD_NO(NUMBER), BOARD_FILE_NO(NUMBER)를 PK로 갖으면서 BOARD_FILE_NM(VARCHAR2(200)), BOARD_FILE_PATH(VARCHAR2(2000)),
--   ORIGIN_FILE_NM(VARCHAR2(200)) 컬럼을 갖는 T_BOARD_FILE 테이블을 생성하세요.
